[phases.setup]
nixPkgs = ["tesseract"]

[phases.install]
cmds = [
  "pip install -r requirements.txt",
  "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "gunicorn --bind=0.0.0.0:$PORT --workers=1 --timeout=180 --preload app:app"
